name: Build
on:
  pull_request:
    branches:
      - develop
    paths-ignore:
      - 'docs/**'
      - '*.md'
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull Docker image
        run: docker pull devkitpro/devkitarm

      - name: Build project with Make inside the Docker image
        run: |
          docker run --rm -v ${{ github.workspace }}:/ezkernelnew -w /ezkernelnew devkitpro/devkitarm:latest make

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: generated-gba-artifact
          path: ezkernelnew.gba     

  link-to-image:
    name: Link .gba file to kernel image
    runs-on: windows-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: generated-gba-artifact
      
      - name: Link .gba file to kernel image
        run: ./link_to_image.exe

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: ezkernelnew.bin
