name: Setup DevKitPro

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up DevKitPro
      run: |
        sudo apt update
        sudo apt install -y wget
        sudo wget -O /usr/local/bin/pacman https://github.com/icy/pacapt/raw/ng/pacapt
        sudo chmod 755 /usr/local/bin/pacman
        wget https://apt.devkitpro.org/install-devkitpro-pacman
        chmod +x ./install-devkitpro-pacman
        sudo ./install-devkitpro-pacman

    - name: Export environment variables
      run: |
        echo "DEVKITPRO=/opt/devkitpro" >> $GITHUB_ENV
        echo "DEVKITARM=/opt/devkitpro/devkitARM" >> $GITHUB_ENV
